services:
  
  redis:
    image: redis
    ports:
      - 6379:6379

  publisher-postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres

  publisher-server:
    image: hsl-map-publisher
    ports:
      - 4000:4000
    environment:
      - SERVICE=server:production
    volumes:
      - ./output:/output
      - ./fonts:/fonts
  
  publisher-render:
    image: hsl-map-publisher
    ports:
      - 5000:5000
    environment:
      - SERVICE=start:production
    volumes:
      - ./output:/output
      - ./fonts:/fonts
  
  publisher-worker:
    image: hsl-map-publisher
    environment:
      - SERVICE=worker:production
    volumes:
      - ./output:/output
      - ./fonts:/fonts
