name: Build and publish Docker Hub dev image

on:
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: hsldevcom/hsl-map-publisher:dev
          build-args: |
            BUILD_ENV: dev
