name: Build and publish Docker Hub prod image

on:
  push:
    branches:
      - 'master'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.KARTAT_DOCKERHUB_USER }}
          password: ${{ secrets.KARTAT_DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hsldevcom/hsl-map-publisher

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          name: hsldevcom/hsl-map-publisher
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}