name: Build and publish Docker Hub prod image

on:
  push:
    branches:
      - 'master'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.KARTAT_DOCKERHUB_USER }}
          password: ${{ secrets.KARTAT_DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: hsldevcom/hsl-map-publisher

      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short "$GITHUB_SHA")"

      - name: Get image timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d')"

      - name: Build and push timestamped tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ format('hsldevcom/hsl-map-publisher:prod-{0}-{1}', steps.timestamp.outputs.timestamp, steps.commit_hash.outputs.hash)

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: hsldevcom/hsl-map-publisher:prod