---
name: "CI/CD: Continuous integration and continuous deployment"

"on":
  push:
    branches:
      - '**'
    tags:
      - "v*"
  pull_request:

jobs:
  build-check-test-push:
    uses: HSLdevcom/transitdata-shared-workflows/.github/workflows/ci-cd-typescript.yml@feature/megalinter
    secrets: inherit
    with:
      checkAndTestOutsideDocker: true
      performRelease: false
      checkAndTestInsideDocker: false
